baseURL: "https://water-walk.github.io/portfolio/"
title: "Hasuda | Portfolio"
theme: ["hugo-PaperMod"]

enableEmoji: true
minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  description: "Hasuda's portfolio"
  author: "Mizuho Hasuda"
  defaultTheme: light
  disableThemeToggle: true

languages:
  en:
    languageName: "JP"
    weight: 1
    menu:
      main:
        - name: "WORK"
          url: "#work"
          weight: 10
        - name: "PROFILE"
          url: "#profile"
          weight: 20
        - name: "PUBLICATION"
          url: "#publication"
          weight: 30
        - name: "CONTACT"
          url: "#contact"
          weight: 40
markup:
  goldmark:
    renderer:
      unsafe: true